### ISSUE TITLE
Izlash inputi noto'g'ri tarzta tuzilgan

### ISSUE THREAD

**Issue by Javohirshakh** [IlhomYuldoshev/Namanganliklar-repo#4]
divni inputga o'xshatib tuzgansiz va joylashtirgansiz. Aslida boshqacha tuziladi. Butun ko'rinib turgan qism to'liq input bo'lishi kerak. iconka shunga nisbatan absolute qilib qo'yiladi

![image](https://user-images.githubusercontent.com/77332200/134213563-daa60707-c590-418b-b85c-a3cf2d025854.png)

**Comment by IlhomYuldoshev** [comment]
qarab ko'ring endi to'g'ri qilganmanmi
